### ISSUE TITLE
KeyError with debian modules

### ISSUE THREAD

**Issue by x23n5902y** [pulp/squeezer#95]
```
- name: Create a deb repository
  pulp.squeezer.deb_repository:
    pulp_url: '{{ pulp_server_url }}'
    username:  '{{ pulp_admin_username }}'
    password: '{{ pulp_admin_password }}'
    name: test1
    state: present
    description: "test1"
  register: repo_status

```
deb_repository or deb_remote modules fails with

```
The full traceback is:
Traceback (most recent call last):

  File "/tmp/ansible_pulp.squeezer.deb_repository_payload__xdgsx_b/ansible_pulp.squeezer.deb_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/modules/deb_repository.py", line 94, in main

  File "/tmp/ansible_pulp.squeezer.deb_repository_payload__xdgsx_b/ansible_pulp.squeezer.deb_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 311, in process
    entities = self.list()

  File "/tmp/ansible_pulp.squeezer.deb_repository_payload__xdgsx_b/ansible_pulp.squeezer.deb_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 194, in list
    self._list_id, parameters={"limit": PAGE_LIMIT, "offset": offset}

  File "/tmp/ansible_pulp.squeezer.deb_repository_payload__xdgsx_b/ansible_pulp.squeezer.deb_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/openapi.py", line 217, in call
    method, path = self.operations[operation_id]

KeyError: 'repositories_deb_apt_list'
fatal: [x-xxx-x-xxxxx]: FAILED! => changed=false
  invocation:
    module_args:
      description: null
      name: null
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      pulp_url: https://x-xxx-x-xxxxx.domain.tld/
      refresh_api_cache: false
      state: null
      username: admin
      validate_certs: true
  msg: '''repositories_deb_apt_list'''
```

**Comment by x23n5902y** [comment]
```
ok: [x-xxx-x-xxxxx] =>
  pulp_status:
    changed: false
    failed: false
    status:
      database_connection:
        connected: true
      online_content_apps:
      - last_heartbeat: '2022-02-22T13:39:40.264556Z'
        name: 1969@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.512500Z'
        name: 2016@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.542221Z'
        name: 1992@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.051096Z'
        name: 2013@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.051738Z'
        name: 2023@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.054854Z'
        name: 1990@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.216636Z'
        name: 2027@x-xxx-x-xxxxx
      - last_heartbeat: '2022-02-22T13:39:40.258933Z'
        name: 2003@x-xxx-x-xxxxx
      online_workers:
      - last_heartbeat: '2022-02-22T13:39:34.288715Z'
        name: 1706@x-xxx-x-xxxxx.domain.tld
        pulp_created: '2022-02-22T13:31:43.558773Z'
        pulp_href: /pulp/api/v3/workers/8c149b27-1f28-49ba-a5bc-5fcf0c2ff9fd/
      - last_heartbeat: '2022-02-22T13:39:34.312484Z'
        name: 1709@x-xxx-x-xxxxx.domain.tld
        pulp_created: '2022-02-22T13:31:43.548519Z'
        pulp_href: /pulp/api/v3/workers/4aa96f36-8b9f-485c-9780-6b0c15996ed9/
      redis_connection:
        connected: true
      storage:
        free: 2182562394112
        total: 2197945323520
        used: 15382929408
      versions:
      - component: core
        version: 3.14.12
      - component: rpm
        version: 3.14.12
      - component: file
        version: 1.8.2
      - component: deb
        version: 2.14.1
    warnings:
    - 'Notice: Cached api is outdated. Refreshing...'
```

**Comment by x23n5902y** [comment]
Fixed by itself after restarting the Pulp server.. oO
